name: Publish to NPM

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set NPM token
        run: echo "${{ secrets.NPM_TOKEN }}" | npm login --registry=https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public

      - name: Update release notes
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.updateComment({
              issue_number: context.issue.number,
              comment_id: context.comment.id,
              body: `**Release Notes**\n\n${context.issue.body}\n\n**Built and published on ${new Date().toUTCString()}**`
            })
